---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-cleaner
  namespace: default
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-cleaner
subjects:
  - kind: ServiceAccount
    name: k8s-cleaner
    namespace: default
